# Generated by Django 5.1.1 on 2024-09-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attendee', '0001_initial'),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_entrys', models.IntegerField(verbose_name='Numero Entradas')),
                ('idAttendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendee.attendee')),
                ('idEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
