# Generated by Django 4.2 on 2024-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canceled_bool',
            field=models.BooleanField(default=False, verbose_name='Cancel Reservation'),
        ),
    ]
