# Generated by Django 5.1.1 on 2024-09-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Tema'),
        ),
    ]
