# Generated by Django 5.1.1 on 2024-09-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollment_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de inscripción'),
        ),
    ]
