# Generated by Django 5.1.1 on 2024-09-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='opciones',
            field=models.TextField(max_length=500, verbose_name='Opciones'),
        ),
    ]
