# Generated by Django 5.1.1 on 2024-09-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=100, verbose_name='Documento')),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('Email', models.EmailField(max_length=100, verbose_name='Email')),
                ('idRol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
