# Generated by Django 5.1.1 on 2024-09-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Document', '0001_initial'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DucumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.document')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tag.tag')),
            ],
        ),
    ]
