# Generated by Django 5.1.1 on 2024-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
            ],
            options={
                'verbose_name': 'Eventos',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
