# Generated by Django 5.1.1 on 2024-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACT', 'Activo'), ('CAN', 'Cancelado')], default='ACT', max_length=50, verbose_name='Estado'),
        ),
    ]
