# Generated by Django 5.1.1 on 2024-09-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produc', models.CharField(max_length=255)),
                ('descripcion_produc', models.TextField()),
                ('precio_produc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='inventory',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.product'),
        ),
    ]
