# Generated by Django 5.1.1 on 2024-09-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_cantidad_inventory_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='cantidad_disponible',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='product',
            new_name='producto',
        ),
    ]
